### PR TITLE
feat: add gradle builder

### PR DESCRIPTION
**Pull request by jrfaller**

### CODE REVIEW

**Comment by jrfaller** [comment]
Nice! However the configuration is still the same for both Maven and Gradle -> list of Goals and Properties, if you look at GradleBuilder, you'll see it's a little awkward how I use the properties, no?

**Comment by tdegueul** [comment]
We keep the `goals` and just pass a `List<String>` as properties then?

`breakbot.yml` would look like:
```
build:
  args: -x test # Gradle
  args: -Dmaven.test.skip # maven
```

**Comment by jrfaller** [comment]
For gradle it would be OK I guess but for the YAML IIUC it would be 

~~~
build:
  goals: ['toto', 'foo']
  args: ['-x', 'test'] # Gradle
  args: ['-Dmaven.test.skip'] # maven
~~~

**Comment by tdegueul** [comment]
The quotes aren't needed (even for stuff like `-x` surprisingly), but indeed these should be arrays! Alright, I'll implement that.

**Pull request merged**
